language: python
cache: pip
python: 3.6
env: TOXENV=py

matrix:
  include:
    - env: TOXENV=test
    - env: TOXENV=coverage-report
    - env: TOXENV=codecov

install:
  - pip install tox-travis

script:
  - cd src/ && tox
