version: 2
jobs:
    build:
        docker:
            -   image: circleci/<language>:<versionTAG> # TODO(ope) new to support spaces in scalar strings
        steps:
            -   checkout
            -   run: <command>
    test:
        docker:
            -   image: circleci/<language>:<versionTAG>
        steps:
            -   checkout
            -   run: <command>
    workflows:
        version: 2
        build_and_test:
            jobs:
                -   build
                -   test
